In [2]:
# 내장함수 예 : input
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

테스트


In [4]:
# List를 이용한 다차원 배열
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]  # 실수 list를 생성

In [5]:
# flVal 3개를 리스트로 구성하여 arVal 다차원 배열을 생성
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [6]:
# arVal은 다차원 배열이므로, arVal[n] 인덱스 연산을 통해 n차원 배열 값을 출력
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [7]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [8]:
arVal[1][2]

3.14

In [9]:
# 1 차원 값을 변환하여 다른 값을 대입 했을때의 다차원 배열
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [10]:
arVal[0][2]

't'

In [11]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [27]:
# numpy 패치지를 import 
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [28]:
arData.sum()

15.44

In [29]:
arVal.sum()

NameError: name 'arVal' is not defined

In [ ]:
print(type(arVal))
print(type(arData))

In [30]:
# 배열에 대한 표준편차 출력
arData.std()

1.4717934637713266

In [31]:
# 배열의 누적 합을 출력
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [32]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [33]:
arData ** 2 # 2를 제곱

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [34]:
# 루트를 적용한 값을 출력
np.sqrt(arData)


array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [35]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [36]:
arVal.sum(axis=0) # 축(axis)이 0일 경우 세로 축의 합을 출력

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [37]:
arVal.sum(axis=1) # 축(axis)이 0일 경우 가로 축의 합을 출력

array([15.44  , 58.5096])

In [38]:
# NumPy.array를 사용한 코드
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [39]:
# NumPy.zeros를 사용한 코드
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [40]:
# pandas import
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [41]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [42]:
pandas_series[0]

30

In [43]:
pandas_series[0][1]

IndexError: invalid index to scalar variable.

In [44]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [45]:
# DataFrame의 index를 표시
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [46]:
# DataFrame의 column을 표시
df.columns

Index(['score'], dtype='object')

In [47]:
# DataFrame의index 중에서 국어에 해당하는 값을 출력
df.loc['국어']   # ix 함수가 최근 제거되어 loc를 써야 동작

score    30
Name: 국어, dtype: int64

In [48]:
# DataFrame의 값을 모두 합한 결과를 출력
df.sum()

score    60
dtype: int64

In [49]:
# DataFrame의 각 colimn 값의 제곱을 출력
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [50]:
# DataFrame에 score2 라는 칼럼을 추가하고 값을 입력
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [51]:
# DataFrame 함수를 이용하여 column을 추가할 수 있음
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [52]:
# column 삭제
del df['score']

In [53]:
# index 를 맞추기 않았을 경우
df['score2'] = (90, 90, 90, 100)

ValueError: Length of values (4) does not match length of index (3)

In [54]:
# index 를 맞추기 않았을 경우
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [55]:
# join() 함수를 이용하여 2개의 DataFrame을 하나로 합칠 수 있음
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [56]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [57]:
# 난수를 이용한 임의의 값 생성
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']

df

A         B         C         D         E
0  1.408057 -0.954602 -1.055140  0.544542 -0.185835
1 -0.929654  0.204281  0.053876 -0.524366 -0.916594
2 -0.752061 -0.875478  0.488946 -0.622095 -0.180357
3  1.193434 -1.144722  0.486438  0.057276 -0.102194
4 -2.935577  1.837952  1.718464  0.952697 -0.118033

In [58]:
# 최대값
df.max()

A    1.408057
B    1.837952
C    1.718464
D    0.952697
E   -0.102194
dtype: float64

In [59]:
# 최소값
df.min()

A   -2.935577
B   -1.144722
C   -1.055140
D   -0.622095
E   -0.916594
dtype: float64

In [60]:
# 평균
df.mean()

A   -0.403160
B   -0.186514
C    0.338517
D    0.081611
E   -0.300603
dtype: float64

In [61]:
# 표준편차
df.std()

A    1.777757
B    1.248397
C    0.996502
D    0.677513
E    0.346329
dtype: float64

In [62]:
# 누적값
df.cumsum()

A         B         C         D         E
0  1.408057 -0.954602 -1.055140  0.544542 -0.185835
1  0.478403 -0.750320 -1.001264  0.020176 -1.102429
2 -0.273659 -1.625799 -0.512318 -0.601918 -1.282786
3  0.919775 -2.770521 -0.025880 -0.544642 -1.384980
4 -2.015802 -0.932569  1.692584  0.408055 -1.503013

In [63]:
# DataFrame의 통계적 요약
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -0.403160 -0.186514  0.338517  0.081611 -0.300603
std    1.777757  1.248397  0.996502  0.677513  0.346329
min   -2.935577 -1.144722 -1.055140 -0.622095 -0.916594
25%   -0.929654 -0.954602  0.053876 -0.524366 -0.185835
50%   -0.752061 -0.875478  0.486438  0.057276 -0.180357
75%    1.193434  0.204281  0.488946  0.544542 -0.118033
max    1.408057  1.837952  1.718464  0.952697 -0.102194

In [64]:
# Group by를 이용한 DataFrame의 그룹화
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0  1.408057 -0.954602 -1.055140  0.544542 -0.185835        X
1 -0.929654  0.204281  0.053876 -0.524366 -0.916594        Y
2 -0.752061 -0.875478  0.488946 -0.622095 -0.180357        X
3  1.193434 -1.144722  0.486438  0.057276 -0.102194        Y
4 -2.935577  1.837952  1.718464  0.952697 -0.118033        Z

In [65]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X         0.327998 -0.915040 -0.283097 -0.038776 -0.183096
Y         0.131890 -0.470220  0.270157 -0.233545 -0.509394
Z        -2.935577  1.837952  1.718464  0.952697 -0.118033